In [39]:
import numpy as np
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [40]:
type(a)

numpy.ndarray

In [41]:
print(a[:2])
print(a[3])
a[0] = 5.
a

[1. 4.]
8.0


array([5., 4., 5., 8.])

In [42]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)
print(a[0,0])
print(a[0,1])
print(a[1,:])
print(a[:,2])
print(a[-1:, -2:])

[[1. 2. 3.]
 [4. 5. 6.]]
1.0
2.0
[4. 5. 6.]
[3. 6.]
[[5. 6.]]


In [43]:
print(a.shape)

(2, 3)


In [44]:
print(a.dtype)

float64


In [45]:
print(len(a))

2


In [46]:
print(2 in a, 8 in a)

True False


In [47]:
a = np.array(range(10), float)
print(a)
a = a.reshape((5, 2))
a

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [48]:
a = np.array([1, 2, 3], float)
b = a
c =  a.copy()
a[0] = 0
print(a)
print(b)
print(c)

[0. 2. 3.]
[0. 2. 3.]
[1. 2. 3.]


In [49]:
print(list(a))

[0.0, 2.0, 3.0]


In [50]:
s = a.tostring()
print(s)

b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'


<ipython-input-50-d3e3b7c08477>:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  s = a.tostring()


In [51]:
a.fill(0)
a

array([0., 0., 0.])

In [52]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a.flatten()

array([1., 2., 3., 4., 5., 6.])

In [53]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
np.concatenate((a, b, c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [54]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)
print(np.concatenate((a,b), axis=0))
np.concatenate((a,b), axis=1)

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]


array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])